run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Staticcheck is go vet on steroids
    - unused        # Check for unused code
    - misspell      # Finds commonly misspelled English words

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (os.Unsetenv)
      - (os.Setenv)

  govet:
    enable-all: true
    disable:
      - shadow  # Can be overly strict
      - fieldalignment  # Optimization not always necessary

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - revive

    # Ignore long lines in generated files
    - path: (.*)?_gen\.go
      linters:
        - lll

output:
  sort-results: true
